import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { SysMLv2ExtendedGeneratedModule, SysMLv2ExtendedGeneratedSharedModule } from './generated/module.js';
import { SysMLv2ExtendedValidator, registerValidationChecks } from './sys-m-lv-2-extended-validator.js';
// 👇 新增导入：引入我们编写的语义高亮引擎
import { SysMLv2ExtendedSemanticTokenProvider } from './sys-m-lv-2-extended-semantic-tokens.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SysMLv2ExtendedAddedServices = {
    validation: {
        SysMLv2ExtendedValidator: SysMLv2ExtendedValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SysMLv2ExtendedServices = LangiumServices & SysMLv2ExtendedAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SysMLv2ExtendedModule: Module<SysMLv2ExtendedServices, PartialLangiumServices & SysMLv2ExtendedAddedServices> = {
    validation: {
        SysMLv2ExtendedValidator: () => new SysMLv2ExtendedValidator()
    },
    // 👇 新增 lsp 节点：将高亮引擎注入到 Langium 的依赖注入容器中
    lsp: {
        SemanticTokenProvider: (services) => new SysMLv2ExtendedSemanticTokenProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 * - Langium default shared services
 * - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 * - Langium default language-specific services
 * - Services generated by langium-cli
 * - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSysMLv2ExtendedServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    SysMLv2Extended: SysMLv2ExtendedServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        SysMLv2ExtendedGeneratedSharedModule
    );
    const SysMLv2Extended = inject(
        createDefaultModule({ shared }),
        SysMLv2ExtendedGeneratedModule,
        SysMLv2ExtendedModule
    );
    shared.ServiceRegistry.register(SysMLv2Extended);
    registerValidationChecks(SysMLv2Extended);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, SysMLv2Extended };
}