import type { SysMLModel } from 'sys-m-lv-2-extended-language';
import { createSysMLv2ExtendedServices, SysMLv2ExtendedLanguageMetaData } from 'sys-m-lv-2-extended-language';
import chalk from 'chalk';
import { Command } from 'commander';
import { extractAstNode } from './util.js';
import { generateJavaScript } from './generator.js';
import { NodeFileSystem } from 'langium/node';
import * as url from 'node:url';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';

// Convert ESM module URL to directory path
const __dirname = url.fileURLToPath(new URL('.', import.meta.url));

// Path to package.json file for version information
const packagePath = path.resolve(__dirname, '..', 'package.json');
// Read package.json content asynchronously
const packageContent = await fs.readFile(packagePath, 'utf-8');

/**
 * Main code generation action handler
 * Processes the input SysML v2 model file and generates corresponding C++ code
 * @param fileName Path to the input SysML v2 model file
 * @param opts Generation options including output destination directory
 */
export const generateAction = async (fileName: string, opts: GenerateOptions): Promise<void> => {
    // Create SysML v2 extended language services with Node.js file system support
    const services = createSysMLv2ExtendedServices(NodeFileSystem).SysMLv2Extended;
    
    // Mapping correction: Use SysMLModel root node generated by 8-tuple theory frontend parsing layer
    const model = await extractAstNode<SysMLModel>(fileName, services);
    
    // Invoke code generator (Placeholder for UR and C operators implementation)
    const generatedFilePath = generateJavaScript(model, fileName, opts.destination);
    
    // Print success message with green color
    console.log(chalk.green(`ASM translation completed successfully: ${generatedFilePath}`));
};

/**
 * Type definition for code generation command options
 */
export type GenerateOptions = {
    destination?: string;
}

/**
 * CLI program entry point
 * Sets up command line interface using Commander.js
 */
export default function(): void {
    // Create new Commander program instance
    const program = new Command();

    // Set program version from package.json
    program.version(JSON.parse(packageContent).version);

    // Get supported file extensions from language metadata
    const fileExtensions = SysMLv2ExtendedLanguageMetaData.fileExtensions.join(', ');
    
    // Configure 'generate' command
    program
        .command('generate')
        .argument('<file>', `source file (possible file extensions: ${fileExtensions})`)
        .option('-d, --destination <dir>', 'destination directory of generating')
        // Updated architecture description aligned with your thesis topic
        .description('Parses SysML v2 extension model and translates it to M2 ASM representation')
        .action(generateAction);

    // Parse command line arguments and execute corresponding action
    program.parse(process.argv);
}
